from __future__ import annotations

from dataclasses import dataclass
import re

from docqa.evaluation.cases import EvaluationCase
from docqa.parsing.schema import DocumentChunk


CONFIG_KEYS = (
    "TARGET_DOCUMENT_KEYWORDS",
    "INLINE_TABLE_KEYWORDS",
    "DOMAIN_FOCUS_TERMS",
    "QUERY_TABLE_TERMS",
    "QUERY_NUMERIC_TERMS",
    "QUERY_DEFINITION_TERMS",
    "QUERY_GENERIC_PHRASES",
    "QUERY_OCR_REPLACEMENTS",
    "GENERIC_AMOUNT_EXPANSION",
)


@dataclass(frozen=True)
class DomainConfigPromptInput:
    business_scene: str
    chunks: list[DocumentChunk]
    cases: list[EvaluationCase]
    max_chunks: int = 10
    max_chunk_chars: int = 700


def build_domain_config_prompt(prompt_input: DomainConfigPromptInput) -> str:
    sampled_chunks = _sample_chunks(prompt_input.chunks, prompt_input.max_chunks)
    chunk_text = "\n\n".join(
        f"[chunk_id={chunk.chunk_id}, page={chunk.page}, type={chunk.chunk_type}]\n"
        f"{_trim(chunk.text, prompt_input.max_chunk_chars)}"
        for chunk in sampled_chunks
    )
    questions = "\n".join(
        f"- {case.case_type}: {case.question} -> {case.expected_behavior}"
        for case in prompt_input.cases
    )

    return f"""你是一个文档问答 Agent 的领域配置助手。

目标：
为一个 RAG 文档问答系统生成领域配置关键词，用于表格识别、查询意图分类、证据聚焦、OCR 常见错字修正和模糊查询改写。

系统支持以下配置项：
- TARGET_DOCUMENT_KEYWORDS：用于校验索引是否属于目标文档
- INLINE_TABLE_KEYWORDS：用于判断文本块是否像表格
- DOMAIN_FOCUS_TERMS：用于答案证据片段聚焦
- QUERY_TABLE_TERMS：用于判断用户问题是否是表格查询
- QUERY_NUMERIC_TERMS：用于判断用户问题是否是数值查询
- QUERY_DEFINITION_TERMS：用于判断用户问题是否是定义/说明类查询
- QUERY_GENERIC_PHRASES：用于删除问题中的泛化空话
- QUERY_OCR_REPLACEMENTS：用于修正 OCR 或输入错字，格式为 原词=>修正词
- GENERIC_AMOUNT_EXPANSION：用于“金额是多少？”这类模糊问题的查询扩展

业务场景：
{prompt_input.business_scene}

文档片段：
{chunk_text}

典型问题：
{questions}

要求：
1. 只输出 .env 格式配置，不要解释。
2. 每个配置项用逗号分隔。
3. QUERY_OCR_REPLACEMENTS 使用 A=>B 格式，多个规则用逗号分隔。
4. 不要生成过宽泛的词，例如“内容”“信息”“数据”。
5. 关键词应优先选择文档中真实出现的字段名、栏目名、条款名、业务名词。
6. 如果某项不确定，也要给出保守候选。

输出格式：
TARGET_DOCUMENT_KEYWORDS=...
INLINE_TABLE_KEYWORDS=...
DOMAIN_FOCUS_TERMS=...
QUERY_TABLE_TERMS=...
QUERY_NUMERIC_TERMS=...
QUERY_DEFINITION_TERMS=...
QUERY_GENERIC_PHRASES=...
QUERY_OCR_REPLACEMENTS=...
GENERIC_AMOUNT_EXPANSION=...
"""


def parse_env_suggestions(text: str) -> dict[str, str]:
    suggestions: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key in CONFIG_KEYS:
            suggestions[key] = _sanitize_env_value(value)
    return suggestions


def format_env_suggestions(suggestions: dict[str, str]) -> str:
    lines = [
        "# Suggested domain config generated by LLM.",
        "# Review manually and validate with scripts/eval.py before copying to .env.",
    ]
    for key in CONFIG_KEYS:
        lines.append(f"{key}={suggestions.get(key, '')}")
    return "\n".join(lines) + "\n"


def _sample_chunks(chunks: list[DocumentChunk], max_chunks: int) -> list[DocumentChunk]:
    table_chunks = [chunk for chunk in chunks if chunk.chunk_type == "table"]
    other_chunks = [chunk for chunk in chunks if chunk.chunk_type != "table"]
    sampled: list[DocumentChunk] = []
    for group in (table_chunks, other_chunks):
        for chunk in group:
            if chunk not in sampled:
                sampled.append(chunk)
            if len(sampled) >= max_chunks:
                return sampled
    return sampled


def _trim(text: str, max_chars: int) -> str:
    compact = "\n".join(line.strip() for line in text.splitlines() if line.strip())
    if len(compact) <= max_chars:
        return compact
    return compact[: max_chars - 3] + "..."


def _sanitize_env_value(value: str) -> str:
    value = value.strip().strip("`").strip()
    value = re.sub(r"[\r\n]+", " ", value)
    return value
